// src/components/solid/SocialButton.tsx
import { JSX } from 'solid-js';
import classNames from 'classnames';
import { Button } from './Button';

interface SocialButtonProps {
    href: string;
    children: JSX.Element;
    class?: string;
}

export default function SocialButton(props: SocialButtonProps) {
    return (
        <Button
            href={props.href}
            target="_blank"
            variant="text"
        >
            {props.children}
        </Button>
    );
}

// components/SocialButton.tsx
import React from "react";
import classNames from "classnames";
import Link from "next/link";

import { Button } from "@/design-system/Button";

type Props = {
  children: React.ReactNode;
  href: string;
};

const SocialButton = ({ children, href }: Props) => {
  return (
    <Button
      target="_blank"
      variant="text"
      href={href}
    >
      {children}
    </Button>
  );
};

export default SocialButton;
